name: timeseries
version: 1.0.0
author: Tony Humbert
description: timeseries functionality for Dart
sdk: '>=1.24.0 <2.0.0-dev.infinity'
dependencies:
  date:
      git:
        url: git://github.com/thumbert/date.git
  func: ^1.0.0
  intl: ^0.14.0
  logging: any
  logging_handlers: any
  timezone: ">=0.4.3 <0.5.0"
  test: '>=0.12.17 <0.13.0'
  tuple: '>=1.0.0 <2.0.0'
