name: timeseries
version: 2.0.1
author: Tony Humbert
description: timeseries functionality for Dart
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  date:
      git:
        url: git://github.com/thumbert/date.git
  intl: '>=0.14.0 <1.0.0'
  timezone: ^0.5.0-dev-3
  tuple: '>=1.0.0 <2.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: '>=1.3.0 <2.0.0'
