name: timeseries
version: 3.0.1
author: Tony Humbert
description: timeseries functionality for Dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  date:
      git:
        url: git://github.com/thumbert/date.git
  intl: ^0.17.0
  more: ^3.0.1
  timezone: ^0.7.0
  tuple: ^2.0.0

dev_dependencies:
  dama:
    git:
      url: git://github.com/thumbert/dama.git
  pedantic: ^1.11.0
  test: ^1.16.5
