name: timeseries
version: 3.0.4
description: timeseries functionality for Dart
publish_to: none
environment:
  sdk: ^3.0.2

dependencies:
  date:
    git: https://github.com/thumbert/date.git
  intl: ^0.18.1
  more: ^3.7.1
  timezone: ^0.9.2
  tuple: ^2.0.0

dev_dependencies:
  dama:
    git: https://github.com/thumbert/dama.git
  lints: ^2.0.0
  test: ^1.24.3
