name: timeseries
version: 0.0.1
author: Tony Humbert
description: timeseries functionality for Dart
dependencies:
  date:
      git:
        url: git://github.com/thumbert/date.git
  intl: '^0.14.0'
  logging: any
  logging_handlers: any
  timezone: ">=0.4.3 <0.5.0"
  test: '>=0.12.17 <0.13.0'
  tuple: '>=1.0.0 <2.0.0'
