name: timeseries
version: 2.1.1
author: Tony Humbert
description: timeseries functionality for Dart
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  date:
    git:
      url: git://github.com/thumbert/date.git
      ref: 2.5.0
  intl: '>=0.14.0 <1.0.0'
  timezone: ^0.5.0-dev-3
  tuple: '>=1.0.0 <2.0.0'

dev_dependencies:
  dama:
    git:
      url: git://github.com/thumbert/dama.git
      ref: non-null
  pedantic: ^1.9.0
  test: '>=1.3.0 <2.0.0'
